<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Peatükk 4 Poissoni regressioon | Kvantitatiivne andmeanalüüs</title>
  <meta name="description" content="Peatükk 4 Poissoni regressioon | Kvantitatiivne andmeanalüüs" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Peatükk 4 Poissoni regressioon | Kvantitatiivne andmeanalüüs" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Peatükk 4 Poissoni regressioon | Kvantitatiivne andmeanalüüs" />
  
  
  

<meta name="author" content="Marko Sõmer" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="3-logistiline-regressioon.html"/>
<link rel="next" href="5-mitmetasandiline-regressioon.html"/>
<script src="assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="assets/tabwid-1.1.0/tabwid.css" rel="stylesheet" />
<link href="assets/tabwid-1.1.0/scrool.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="custom/custom_styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class='before'><a href="./">Kvant</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Alustuseks</a></li>
<li class="part"><span><b>I Meeldetuletus</b></span></li>
<li class="chapter" data-level="1" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html"><i class="fa fa-check"></i><b>1</b> Sissejuhatus R-i</a>
<ul>
<li class="chapter" data-level="1.1" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html#päris-algus"><i class="fa fa-check"></i><b>1.1</b> Päris algus</a></li>
<li class="chapter" data-level="1.2" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html#andmetega-töötamine"><i class="fa fa-check"></i><b>1.2</b> Andmetega töötamine</a></li>
<li class="chapter" data-level="1.3" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html#r-markdown"><i class="fa fa-check"></i><b>1.3</b> R markdown</a></li>
<li class="chapter" data-level="1.4" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html#andmegraafika"><i class="fa fa-check"></i><b>1.4</b> Andmegraafika</a></li>
<li class="chapter" data-level="1.5" data-path="1-sissejuhatus-r-i.html"><a href="1-sissejuhatus-r-i.html#edasiseks-lugemiseks"><i class="fa fa-check"></i><b>1.5</b> Edasiseks lugemiseks</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html"><i class="fa fa-check"></i><b>2</b> Lineaarne regressioon</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#lihtne-lineaarne-regressioon"><i class="fa fa-check"></i><b>2.1</b> Lihtne lineaarne regressioon</a></li>
<li class="chapter" data-level="2.2" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#regressioon-r-is"><i class="fa fa-check"></i><b>2.2</b> Regressioon R-is</a></li>
<li class="chapter" data-level="2.3" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#regressiooni-jäägid"><i class="fa fa-check"></i><b>2.3</b> Regressiooni jäägid</a></li>
<li class="chapter" data-level="2.4" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#regressioonimudeli-sobitumine"><i class="fa fa-check"></i><b>2.4</b> Regressioonimudeli sobitumine</a></li>
<li class="chapter" data-level="2.5" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#kategoriaalsed-tunnused-regressioonis"><i class="fa fa-check"></i><b>2.5</b> Kategoriaalsed tunnused regressioonis</a></li>
<li class="chapter" data-level="2.6" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#mitmene-regressioon"><i class="fa fa-check"></i><b>2.6</b> Mitmene regressioon</a></li>
<li class="chapter" data-level="2.7" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#koosmõjud"><i class="fa fa-check"></i><b>2.7</b> Koosmõjud</a></li>
<li class="chapter" data-level="2.8" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#mudelite-võrdlemine"><i class="fa fa-check"></i><b>2.8</b> Mudelite võrdlemine</a></li>
<li class="chapter" data-level="2.9" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#regressioonimudeli-eeldused"><i class="fa fa-check"></i><b>2.9</b> Regressioonimudeli eeldused</a></li>
<li class="chapter" data-level="2.10" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#kuidas-eelduste-täidetust-hinnata"><i class="fa fa-check"></i><b>2.10</b> Kuidas eelduste täidetust hinnata?</a></li>
<li class="chapter" data-level="2.11" data-path="2-lineaarne-regressioon.html"><a href="2-lineaarne-regressioon.html#tunnuste-transformatsioonid"><i class="fa fa-check"></i><b>2.11</b> Tunnuste transformatsioonid</a></li>
</ul></li>
<li class="part"><span><b>II Üldistatud lineaarsed mudelid</b></span></li>
<li class="chapter" data-level="3" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html"><i class="fa fa-check"></i><b>3</b> Logistiline regressioon</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#šansid"><i class="fa fa-check"></i><b>3.1</b> Šansid</a></li>
<li class="chapter" data-level="3.2" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#logit"><i class="fa fa-check"></i><b>3.2</b> Logit</a></li>
<li class="chapter" data-level="3.3" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#logit-mudel"><i class="fa fa-check"></i><b>3.3</b> Logit mudel</a></li>
<li class="chapter" data-level="3.4" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#mudeli-tõlgendus"><i class="fa fa-check"></i><b>3.4</b> Mudeli tõlgendus</a></li>
<li class="chapter" data-level="3.5" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#logistiline-regressioon-r-is"><i class="fa fa-check"></i><b>3.5</b> Logistiline regressioon R-is</a></li>
<li class="chapter" data-level="3.6" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#mudeli-kvaliteet"><i class="fa fa-check"></i><b>3.6</b> Mudeli kvaliteet</a></li>
<li class="chapter" data-level="3.7" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#predict"><i class="fa fa-check"></i><b>3.7</b> Predict</a></li>
<li class="chapter" data-level="3.8" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#marginaalsed-efektid"><i class="fa fa-check"></i><b>3.8</b> Marginaalsed efektid</a></li>
<li class="chapter" data-level="3.9" data-path="3-logistiline-regressioon.html"><a href="3-logistiline-regressioon.html#prognoosi-täpsus"><i class="fa fa-check"></i><b>3.9</b> Prognoosi täpsus</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html"><i class="fa fa-check"></i><b>4</b> Poissoni regressioon</a>
<ul>
<li class="chapter" data-level="4.1" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html#mudeli-tõlgendus-1"><i class="fa fa-check"></i><b>4.1</b> Mudeli tõlgendus</a></li>
<li class="chapter" data-level="4.2" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html#poissoni-regressiooni-eeldused"><i class="fa fa-check"></i><b>4.2</b> Poissoni regressiooni eeldused</a></li>
<li class="chapter" data-level="4.3" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html#mudeli-hindamine-r-is"><i class="fa fa-check"></i><b>4.3</b> Mudeli hindamine R-is</a></li>
<li class="chapter" data-level="4.4" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html#mudeli-eelduste-kontroll"><i class="fa fa-check"></i><b>4.4</b> Mudeli eelduste kontroll</a></li>
<li class="chapter" data-level="4.5" data-path="4-poissoni-regressioon.html"><a href="4-poissoni-regressioon.html#mudeli-sobivus-model-fit"><i class="fa fa-check"></i><b>4.5</b> Mudeli sobivus (<em>model fit</em>)</a></li>
</ul></li>
<li class="part"><span><b>III Mitmetasandiline regressioon</b></span></li>
<li class="chapter" data-level="5" data-path="5-mitmetasandiline-regressioon.html"><a href="5-mitmetasandiline-regressioon.html"><i class="fa fa-check"></i><b>5</b> Mitmetasandiline regressioon</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5-mitmetasandiline-regressioon.html"><a href="5-mitmetasandiline-regressioon.html#andmete-hierarhiline-struktuur"><i class="fa fa-check"></i><b>5.1</b> Andmete hierarhiline struktuur</a></li>
<li class="chapter" data-level="5.2" data-path="5-mitmetasandiline-regressioon.html"><a href="5-mitmetasandiline-regressioon.html#mitmetasandiline-analüüs"><i class="fa fa-check"></i><b>5.2</b> Mitmetasandiline analüüs</a></li>
<li class="chapter" data-level="5.3" data-path="5-mitmetasandiline-regressioon.html"><a href="5-mitmetasandiline-regressioon.html#mitmetasandilise-analüüsi-eeldused"><i class="fa fa-check"></i><b>5.3</b> Mitmetasandilise analüüsi eeldused</a></li>
<li class="chapter" data-level="5.4" data-path="5-mitmetasandiline-regressioon.html"><a href="5-mitmetasandiline-regressioon.html#mitemtasandiline-analüüs-ris"><i class="fa fa-check"></i><b>5.4</b> Mitemtasandiline analüüs Ris</a></li>
</ul></li>
<li class="part"><span><b>IV Valimiuuringud</b></span></li>
<li class="chapter" data-level="6" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html"><i class="fa fa-check"></i><b>6</b> Valimiuuringud</a>
<ul>
<li class="chapter" data-level="6.1" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#tõenäosuslik-valim-probability-sample"><i class="fa fa-check"></i><b>6.1</b> Tõenäosuslik valim (probability sample)</a></li>
<li class="chapter" data-level="6.2" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#kaalud"><i class="fa fa-check"></i><b>6.2</b> Kaalud</a></li>
<li class="chapter" data-level="6.3" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#valimidisain"><i class="fa fa-check"></i><b>6.3</b> Valimidisain</a></li>
<li class="chapter" data-level="6.4" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#tulemuste-valimidisaini-suhtes-korrigeerimine"><i class="fa fa-check"></i><b>6.4</b> Tulemuste valimidisaini suhtes korrigeerimine</a></li>
<li class="chapter" data-level="6.5" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#küsitlusandmed-ris"><i class="fa fa-check"></i><b>6.5</b> Küsitlusandmed Ris</a></li>
<li class="chapter" data-level="6.6" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#valimiandmete-analüüs"><i class="fa fa-check"></i><b>6.6</b> Valimiandmete analüüs</a></li>
<li class="chapter" data-level="6.7" data-path="6-valimiuuringud.html"><a href="6-valimiuuringud.html#plausible-values"><i class="fa fa-check"></i><b>6.7</b> Plausible values</a></li>
</ul></li>
<li class="part"><span><b>V SEM</b></span></li>
<li class="chapter" data-level="7" data-path="7-struktuurivõrrandite-mudelid.html"><a href="7-struktuurivõrrandite-mudelid.html"><i class="fa fa-check"></i><b>7</b> Struktuurivõrrandite mudelid</a>
<ul>
<li class="chapter" data-level="7.1" data-path="7-struktuurivõrrandite-mudelid.html"><a href="7-struktuurivõrrandite-mudelid.html#rajaanalüüs"><i class="fa fa-check"></i><b>7.1</b> Rajaanalüüs</a></li>
<li class="chapter" data-level="7.2" data-path="7-struktuurivõrrandite-mudelid.html"><a href="7-struktuurivõrrandite-mudelid.html#faktoranalüüs"><i class="fa fa-check"></i><b>7.2</b> Faktoranalüüs</a></li>
<li class="chapter" data-level="7.3" data-path="7-struktuurivõrrandite-mudelid.html"><a href="7-struktuurivõrrandite-mudelid.html#sruktuurivõrrandite-mudelid"><i class="fa fa-check"></i><b>7.3</b> Sruktuurivõrrandite mudelid</a></li>
<li class="chapter" data-level="7.4" data-path="7-struktuurivõrrandite-mudelid.html"><a href="7-struktuurivõrrandite-mudelid.html#struktuurivõrrandite-mudelid-ris"><i class="fa fa-check"></i><b>7.4</b> Struktuurivõrrandite mudelid Ris</a></li>
</ul></li>
<li class="part"><span><b>VI Klasteranalüüs</b></span></li>
<li class="chapter" data-level="8" data-path="8-klasteranalüüs.html"><a href="8-klasteranalüüs.html"><i class="fa fa-check"></i><b>8</b> Klasteranalüüs</a>
<ul>
<li class="chapter" data-level="8.1" data-path="8-klasteranalüüs.html"><a href="8-klasteranalüüs.html#mis-see-klasteranalüüs-on"><i class="fa fa-check"></i><b>8.1</b> Mis see klasteranalüüs on?</a></li>
<li class="chapter" data-level="8.2" data-path="8-klasteranalüüs.html"><a href="8-klasteranalüüs.html#hierarhiline-klasteranalüüs"><i class="fa fa-check"></i><b>8.2</b> Hierarhiline klasteranalüüs</a></li>
<li class="chapter" data-level="8.3" data-path="8-klasteranalüüs.html"><a href="8-klasteranalüüs.html#k-keskmiste-k-means-klasterdamine"><i class="fa fa-check"></i><b>8.3</b> K-keskmiste (k-means) klasterdamine</a></li>
<li class="chapter" data-level="8.4" data-path="8-klasteranalüüs.html"><a href="8-klasteranalüüs.html#klasteranalüüsi-tulemi-valiidsus"><i class="fa fa-check"></i><b>8.4</b> Klasteranalüüsi tulemi valiidsus</a></li>
</ul></li>
<li class="appendix"><span><b>LISA</b></span></li>
<li class="chapter" data-level="A" data-path="A-tavaline-lineaarne-regressioon-maatriksarvutusena.html"><a href="A-tavaline-lineaarne-regressioon-maatriksarvutusena.html"><i class="fa fa-check"></i><b>A</b> Tavaline lineaarne regressioon maatriksarvutusena</a></li>
<li class="chapter" data-level="B" data-path="B-delta-meetod.html"><a href="B-delta-meetod.html"><i class="fa fa-check"></i><b>B</b> Delta meetod</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Kvantitatiivne andmeanalüüs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="poissoni-regressioon" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Peatükk 4</span> Poissoni regressioon<a href="4-poissoni-regressioon.html#poissoni-regressioon" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Poissoni regressioon kuulub üldistatud lineaarsete mudelite (GLM) raamistikku ja sellega saame hinnata sõltumatute tunnuste mõju mingile loendavale (<em>count</em>) sõltuvale tunnusele (mitu inimest on kursusel, mitu inimest on poejärjekorras, mitu last on peres jne)<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a>.</p>
<p>Sarnaselt logistilise regressiooniga (ja isegi õigustatumalt) tekib küsimus, et miks me ei saa taoliste tunnuste korral kasutada tavalist lineaarset regressiooni? Loend on ju suhteliselt sarnane tavalisele arvtunnusele. Välja arvatud asjaolu, et nii nagu tõenäosus logistilise regressiooni puhul, ei saa ka loend olla negatiivne. Kui me modelleeriksime loendi tunnust tavalise lineaarse regressiooniga, siis võib vabalt juhtuda, et mingite sõltumatute tunnuste väärtuste korral oleks prognoositav sõltuv tunnus väiksem kui 0. See aga ei ole loendilise tunnuse puhul realistlik. Lisaks, nii nagu ka logistilise regressiooni ja binaarsete sõltuvate tunnuste puhul, tekivad probleemid jääkide struktuuriga (tavaline regressioon eeldab normaaljaotust) ja jääkide dispersiooniga (tavaline regressioon eeldab konstantset hajuvust)<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a>.</p>
<div class="figure"><span style="display:block;" id="fig:pois-dist"></span>
<img src="03-poisson_files/figure-html/pois-dist-1.png" alt="Poissoni jaotus erinevate keskmiste loendusväärtuste (Lambda) korral" width="672" />
<p class="caption">
Joonis 4.1: Poissoni jaotus erinevate keskmiste loendusväärtuste (Lambda) korral
</p>
</div>
<p>Logistilise regressiooni puhul saime tõenäosuse ülemisest piirist lahti seeläbi, et teisendasime tõenäosused šanssideks ning alumise piiri seeläbi, et võtsime šanssidest logaritmid. Loendilise tunnuse puhul meil tunnuse ülemise piiriga probleemi ei ole. Loend võib potentsiaalselt olla lõputu. Alumise piiri puhul saame aga kasutada sedasama logit mudelitest tuttavat logaritmimise nippi. Kui <span class="math inline">\(Y\)</span> on meie hinnatav loendiline sõltuv tunnus ja <span class="math inline">\(x\)</span> seda selgitav sõltumatu tunnus, siis Poissoni regressioonimudel on väljendatav järgmiselt<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a>:</p>
<p><span class="math display">\[log(Y_i)=\beta_0+\beta_1 x_i\]</span>
kui me võtame mõlemast võrrandi pooles eksponendi, saame sama asja väljendada ka nii:</p>
<p><span class="math display">\[Y_i = e^{\beta_0+\beta_1 x_i}\]</span></p>
<p>Eeldame siin, et <span class="math inline">\(Y_i\)</span> järgib Poissoni jaotust. GLM’i sõnavara kasutades ütleme, et mudeli juhuslik komponent (ehk siis sõltuv tunnus) on Poissoni jaotusega ning linkfunktsioonina (funktsiooon, mille abil sõltuva ja sõltumatute tunnuste vaheline mittelineaarne seos muudetakse lineaarseks seoseks) kasutame log-funktsiooni.</p>
<p>Poissoni jaotuse kuju sõltub tunnuse keskmisest (võrdluseks, normaaljaotuse kuju sõltub tunnuse keskmisest ja standardhälbest). Mida suurem on keskmine, seda enam sarnaneb Poissoni jaotus normaaljaotusele (vt joonis 1). Seega suurte loendite puhul saaksime põhimõtteliselt ka tavalist lineaarset regressiooni kasutada (kuigi negatiivsete väärtuste probleem jääb ka sel juhul). Üldiselt on mõistlik Poissoni regressiooni kasutada siis, kui loendite maksimaalsed väärtused ei ole väga suured ja tunnus on eripäraselt Poissoni jaotuse kujuga. Kui meil on tegemist suuremate väärtustega loendiga (näiteks ülikoolide tudengite arvud), siis saame tunnuse näiteks mingi arvuga läbi jagada.</p>
<p>Loendilise tunnuse puhul tuleb tihti ette olukordi, kus tunnuses on palju nulle. Näiteks tunnus, mis kirjeldab bakalaureusetudengite laste arvu. Põhimõtteliselt on muidugi tegemist loendilise tunnusega, aga kuna suuremal osal tudengitest veel ei ole lapsi, siis enamik vaatlusi on paratamatult nullid. Sellise tunnuse jaotus ei vasta väga hästi Poissoni jaotusele ja selle kasutamine Poissoni regressioonimudeliga ei anna tõenäoliselt väga head tulemust<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a>.</p>
<div id="mudeli-tõlgendus-1" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Mudeli tõlgendus<a href="4-poissoni-regressioon.html#mudeli-tõlgendus-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Kuidas me neid regressioonimudeli <span class="math inline">\(\beta_0\)</span> ja <span class="math inline">\(\beta_1\)</span> koefitsiente tõlgendama peaksime? Lineaarse regressiooni puhul oli asi lihtne: vabaliige (<span class="math inline">\(\beta_0\)</span>) oli tõlgendatav <span class="math inline">\(Y\)</span> väärtusena kui <span class="math inline">\(x\)</span> on <span class="math inline">\(0\)</span> ja regressioonikoefitsient (<span class="math inline">\(\beta_1\)</span>) näitas <span class="math inline">\(Y\)</span> muutust kui <span class="math inline">\(x\)</span> muutub ühe ühiku võrra. Logistilise regressiooni puhul pidime aga esmalt koefitsientidest eksponendi võtma ja saime neid seejärel tõlgendada šansside ja šansside suhetena. Mis siis sekord?</p>
<p>Kuna meil on jälle tegemist logaritmidega, siis koefitsientide otsene (lineaarse regressiooni moodi) tõlgendamine on keeruline. Mõistlikum on koefitsientidest jällegi eksponent võtta, misjärel saame vabaliiget tõlgendada tavapärasel moel (<span class="math inline">\(Y\)</span> väärtus kui <span class="math inline">\(x\)</span> on <span class="math inline">\(0\)</span>) ja regressioonikoefitsienti kui <span class="math inline">\(Y\)</span>-i multiplikatiivset muutust kui <span class="math inline">\(x\)</span> muutub ühe ühiku võrra. Ehk kui <span class="math inline">\(\beta_1\)</span> väärtus on näiteks 0.25, siis tema eksponent on <span class="math inline">\(e^{0.25} = exp(0.25) = 1.28\)</span> ja saame järeldada, et kui <span class="math inline">\(x\)</span> kasvab ühe ühiku võrra, siis <span class="math inline">\(Y\)</span> kasvab <span class="math inline">\(1.28\)</span> korda. Teisisõnu, <span class="math inline">\(Y\)</span> kasvab <span class="math inline">\(28\%\)</span>. Või kui <span class="math inline">\(\beta_1\)</span> väärtus on <span class="math inline">\(-0.5\)</span>, siis tema eksponent on <span class="math inline">\(e^{-0.5} = exp(-0.5) = 0.6\)</span> ja saame järeldada, et kui <span class="math inline">\(x\)</span> kasvab ühe ühiku võrra, siis <span class="math inline">\(Y\)</span> kasvab <span class="math inline">\(0.6\)</span> korda (ehk siis tegelikult kahaneb). Kui <span class="math inline">\(\beta = 0\)</span>, siis <span class="math inline">\(e^{0} = 1\)</span> ehk multiplikatiivne efekt on <span class="math inline">\(1\)</span> (<span class="math inline">\(Y\times1\)</span>) ja <span class="math inline">\(Y\)</span> <span class="math inline">\(x\)</span>-i kasvades või kahanedes ei muutu. Kui <span class="math inline">\(\beta &lt; 0\)</span>, siis <span class="math inline">\(Y\)</span> <span class="math inline">\(x\)</span>-i kasvades väheneb, kui <span class="math inline">\(\beta &gt; 0\)</span>, siis <span class="math inline">\(Y\)</span> <span class="math inline">\(x\)</span>-i kasvades kasvab.</p>
</div>
<div id="poissoni-regressiooni-eeldused" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Poissoni regressiooni eeldused<a href="4-poissoni-regressioon.html#poissoni-regressiooni-eeldused" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Sõltuv tunnus <span class="math inline">\(Y\)</span> peaks enam-vähem vastama Poissoni jaotusele (st olema loendiline tunnus).</li>
<li>Vaatlused peavad olema üksteisest sõltumatud (st kogu vaatluste vaheline seos peaks olema kirjeldatud mudeli sõltumatute tunnuste poolt).</li>
<li>Dispersioon (<em>variance</em>) peaks olema võrdne keskmisega. Juhul kui see eeldus ei ole täidetud, ja tihti juhtub, et ei ole, on meil tegemist nn üledispersiooniga (<em>overdispersion</em>). Sellisel juhul tuleks Poissoni mudeli asemel kasutada nn <em>quasipoisson</em>’i mudelit.</li>
<li>Sõltuva tunnuse ja sõltumatute prediktorite seos peaks läbi linkfunktsiooni olema lineaarne.</li>
</ul>
</div>
<div id="mudeli-hindamine-r-is" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Mudeli hindamine R-is<a href="4-poissoni-regressioon.html#mudeli-hindamine-r-is" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="andmete-kirjeldus-ja-ettevalmistus" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Andmete kirjeldus ja ettevalmistus<a href="4-poissoni-regressioon.html#andmete-kirjeldus-ja-ettevalmistus" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Kasutame näitena <em>PhDPublications</em> andmestikku<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a> paketist <em>AER</em>. Andmestikus on loendatud biokeemia doktorantide publikatsioonide arv (tunnus <em>atricles</em>) kolme aasta jooksul. Sõltumatute tunnustena on kasutada:</p>
<ul>
<li><em>gender</em>,</li>
<li><em>married</em> - kas doktorant oli abielus,</li>
<li><em>kids</em> - mitu last doktorandil oli,</li>
<li><em>prestige</em> - kooli maine skoor) ja</li>
<li><em>mentor</em> - juhendaja publikatsioonide arv.</li>
</ul>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="4-poissoni-regressioon.html#cb531-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kui pakett ei ole installitud, </span></span>
<span id="cb531-2"><a href="4-poissoni-regressioon.html#cb531-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tuleb seda teha käsuga: install.packages(&quot;AER&quot;)</span></span>
<span id="cb531-3"><a href="4-poissoni-regressioon.html#cb531-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb531-4"><a href="4-poissoni-regressioon.html#cb531-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Loeme paketi sisse</span></span>
<span id="cb531-5"><a href="4-poissoni-regressioon.html#cb531-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb531-6"><a href="4-poissoni-regressioon.html#cb531-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Võtame andmestiku</span></span>
<span id="cb531-7"><a href="4-poissoni-regressioon.html#cb531-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(PhDPublications)</span>
<span id="cb531-8"><a href="4-poissoni-regressioon.html#cb531-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Paneme andmestikule lihtsama nime</span></span>
<span id="cb531-9"><a href="4-poissoni-regressioon.html#cb531-9" aria-hidden="true" tabindex="-1"></a>phd <span class="ot">&lt;-</span> PhDPublications</span></code></pre></div>
<p>Vaatame artiklite tunnust lähemalt:</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="4-poissoni-regressioon.html#cb532-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(phd)<span class="sc">+</span></span>
<span id="cb532-2"><a href="4-poissoni-regressioon.html#cb532-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> articles), </span>
<span id="cb532-3"><a href="4-poissoni-regressioon.html#cb532-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">1</span>, </span>
<span id="cb532-4"><a href="4-poissoni-regressioon.html#cb532-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, </span>
<span id="cb532-5"><a href="4-poissoni-regressioon.html#cb532-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&#39;black&#39;</span>)<span class="sc">+</span></span>
<span id="cb532-6"><a href="4-poissoni-regressioon.html#cb532-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Ilmselgelt on tegemist loendilise tunnusega. Samas päris Poissoni jaotusega tegemist vist siiski ei ole, kuna tundub, et nulle on selleks natukene liiga palju. ggploti abil saame joonisele panna ka tunnust iseloomustava teoreetilise Poissoni jaotuse (lähtuvalt tunnuse keskmisest ehk <span class="math inline">\(\lambda\)</span> parameetrist). Vaatame kuidas see võrreldes reaalse jaotusega välja näeb:</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="4-poissoni-regressioon.html#cb533-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poissoni jaotuse parameetrina on meil vaja keskmist</span></span>
<span id="cb533-2"><a href="4-poissoni-regressioon.html#cb533-2" aria-hidden="true" tabindex="-1"></a>keskmine <span class="ot">&lt;-</span> <span class="fu">mean</span>(phd<span class="sc">$</span>articles)</span>
<span id="cb533-3"><a href="4-poissoni-regressioon.html#cb533-3" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb533-4"><a href="4-poissoni-regressioon.html#cb533-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># standardiseerime  artiklite arvu, </span></span>
<span id="cb533-5"><a href="4-poissoni-regressioon.html#cb533-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># et saaksime seda jaotusega võrrelda</span></span>
<span id="cb533-6"><a href="4-poissoni-regressioon.html#cb533-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(articles) <span class="sc">%&gt;%</span> </span>
<span id="cb533-7"><a href="4-poissoni-regressioon.html#cb533-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb533-8"><a href="4-poissoni-regressioon.html#cb533-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n_scaled =</span> n<span class="sc">/</span><span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb533-9"><a href="4-poissoni-regressioon.html#cb533-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> articles, <span class="at">y =</span> n_scaled))<span class="sc">+</span></span>
<span id="cb533-10"><a href="4-poissoni-regressioon.html#cb533-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># kasutame stat = &#39;identity&#39;, </span></span>
<span id="cb533-11"><a href="4-poissoni-regressioon.html#cb533-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># st kasutame joonisel olemasolevaid väärtusi</span></span>
<span id="cb533-12"><a href="4-poissoni-regressioon.html#cb533-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (mitte ei lase ggplot&#39;il neid välja arvutada)</span></span>
<span id="cb533-13"><a href="4-poissoni-regressioon.html#cb533-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>, </span>
<span id="cb533-14"><a href="4-poissoni-regressioon.html#cb533-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, </span>
<span id="cb533-15"><a href="4-poissoni-regressioon.html#cb533-15" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&#39;black&#39;</span>)<span class="sc">+</span></span>
<span id="cb533-16"><a href="4-poissoni-regressioon.html#cb533-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dpois funktsioon annab meile poissoni tihedusfunktsiooni</span></span>
<span id="cb533-17"><a href="4-poissoni-regressioon.html#cb533-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> articles, </span>
<span id="cb533-18"><a href="4-poissoni-regressioon.html#cb533-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">dpois</span>(articles, <span class="at">lambda =</span> keskmine)), </span>
<span id="cb533-19"><a href="4-poissoni-regressioon.html#cb533-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">&#39;red&#39;</span>)<span class="sc">+</span></span>
<span id="cb533-20"><a href="4-poissoni-regressioon.html#cb533-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/pois-hist-dist-1.png" width="672" /></p>
<p>Nagu näeme, siis tõesti, nulle on natuke liiga palju ja artiklite loendi jaotus ei vasta jaotuse alguses päris täpselt Poissoni jaotuse kujule. Aga jätame selle asjaolu hetkel tähelepanuta ja kasutame ikkagi Poissoni regressiooni.</p>
<p>Vaatame üle ka teised andmestiku tunnused:</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="4-poissoni-regressioon.html#cb534-1" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb534-2"><a href="4-poissoni-regressioon.html#cb534-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender) <span class="sc">%&gt;%</span> </span>
<span id="cb534-3"><a href="4-poissoni-regressioon.html#cb534-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender `n()`
##   &lt;fct&gt;  &lt;int&gt;
## 1 male     494
## 2 female   421</code></pre>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="4-poissoni-regressioon.html#cb536-1" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb536-2"><a href="4-poissoni-regressioon.html#cb536-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(married) <span class="sc">%&gt;%</span> </span>
<span id="cb536-3"><a href="4-poissoni-regressioon.html#cb536-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   married `n()`
##   &lt;fct&gt;   &lt;int&gt;
## 1 no        309
## 2 yes       606</code></pre>
<p>Soo ja abielu tunnus tunduvad korras olevat, kui välja arvata see, et kuidagi paljud doktorandid paistavad abielus olevat. Aga on nagu on.</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="4-poissoni-regressioon.html#cb538-1" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb538-2"><a href="4-poissoni-regressioon.html#cb538-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(kids) <span class="sc">%&gt;%</span> </span>
<span id="cb538-3"><a href="4-poissoni-regressioon.html#cb538-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##    kids `n()`
##   &lt;int&gt; &lt;int&gt;
## 1     0   599
## 2     1   195
## 3     2   105
## 4     3    16</code></pre>
<p>Laste tunnus on originaalis arvuline. Me kindlasti ei taha nelja väärtusega tunnust arvulisena käsitleda. Parem oleks see faktoriks teha ja seda mudelis kategoriaalsena käsitleda. Antud juhul, kuna lastetuid doktorante on niivõrd palju, oleks vast kõige mõistlik see tunnus üldse binaarseks teha, st kas on või ei ole lapsi (kuigi teoreetiliselt võiks ju eeldada, et laste arv võib mõjutada artiklite kirjutamiseks jäävat aega, siis siin, mulle tundub, on laste arvu variatiivsus selle kasutamiseks liiga väike).</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="4-poissoni-regressioon.html#cb540-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kasutame laste arvu teisendamiseks ifelse() funktsiooni</span></span>
<span id="cb540-2"><a href="4-poissoni-regressioon.html#cb540-2" aria-hidden="true" tabindex="-1"></a><span class="co"># vajadusel vaadake sellekohast abiinfot ?ifelse</span></span>
<span id="cb540-3"><a href="4-poissoni-regressioon.html#cb540-3" aria-hidden="true" tabindex="-1"></a>phd <span class="ot">&lt;-</span> phd <span class="sc">%&gt;%</span> </span>
<span id="cb540-4"><a href="4-poissoni-regressioon.html#cb540-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">kids2 =</span> <span class="fu">ifelse</span>(kids <span class="sc">==</span> <span class="dv">0</span>, <span class="st">&#39;Ei&#39;</span>, <span class="st">&#39;Jah&#39;</span>))</span>
<span id="cb540-5"><a href="4-poissoni-regressioon.html#cb540-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb540-6"><a href="4-poissoni-regressioon.html#cb540-6" aria-hidden="true" tabindex="-1"></a><span class="co"># kontrollime uut tunnust</span></span>
<span id="cb540-7"><a href="4-poissoni-regressioon.html#cb540-7" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb540-8"><a href="4-poissoni-regressioon.html#cb540-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(kids, kids2) <span class="sc">%&gt;%</span> </span>
<span id="cb540-9"><a href="4-poissoni-regressioon.html#cb540-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 4 x 3
## # Groups:   kids [4]
##    kids kids2 `n()`
##   &lt;int&gt; &lt;chr&gt; &lt;int&gt;
## 1     0 Ei      599
## 2     1 Jah     195
## 3     2 Jah     105
## 4     3 Jah      16</code></pre>
<p>Pidevast tunnusest ülevaate saamiseks on mugav kasutada histogrammi:</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="4-poissoni-regressioon.html#cb542-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(phd<span class="sc">$</span>prestige)</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>PhD programmi maine küsimus tundub suht OK.</p>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="4-poissoni-regressioon.html#cb543-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(phd<span class="sc">$</span>mentor)</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Juhendaja artiklit arvu tunnus on iseenesest samuti loendav tunnus (kuigi Poissoni jaotust see samuti päris täpselt ei järgi).</p>
</div>
<div id="poissoni-mudeli-defineerimine" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Poissoni mudeli defineerimine<a href="4-poissoni-regressioon.html#poissoni-mudeli-defineerimine" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vaatame esmalt kuidas sugu artiklite avaldamist mõjutab. Defineerime mudeli kasutades <code>glm()</code> funktsiooni ja selles <code>family =</code> argumendina <code>poisson()</code> funktsiooni (kõlbaks ka <code>family = "poisson"</code> või <code>family = poisson</code>). <code>poisson()</code> funktsiooni puhul on vaikimisi eeldatud linkfunktsioonina <code>log</code>-linki, kuid vajadusel saaksime ka mingit muud linkfunktsiooni kasutada või selle eksplitsiitselt välja tuua: <code>poisson(link = 'log')</code>. Salvestame mudeli kõigepealt andmeobjektiks ning seejärel uurime seda <code>summary()</code> funktsiooniga.</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="4-poissoni-regressioon.html#cb544-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender, <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> phd)</span>
<span id="cb544-2"><a href="4-poissoni-regressioon.html#cb544-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender, family = poisson(), data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9404  -1.7148  -0.4119   0.4139   7.3221  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.63265    0.03279  19.293  &lt; 2e-16 ***
## genderfemale -0.24718    0.05187  -4.765 1.89e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1794.4  on 913  degrees of freedom
## AIC: 3466.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Nagu näeme, siis Poissoni regressiooni väljund on praktiliselt identne logistilise regressiooni väljundiga (mis on ka loogiline, kuna mõlemad on loodud sama funktsiooniga).</p>
<p>Tõlgendame kõigepealt regressioonikoefitsiente. Nagu eelnevalt mainitud, siis tuleks neist eelnevalt eksponent võtta. Aga ka ilma selleta saame öelda, et naised on meestest vähem artikleid avaldanud. Mehed on antud juhul referentsgrupp ning <em>genderfemale</em> koefitsient kirjeldab naiste erinevust meestest. Kuna koefitsient on negatiivne, siis saame järeldada, et keskmine artiklite arv on naiste hulgas väiksem kui meeste hulgas. Aga et teada saada kui palju väiksem, peame koefitsientidest eksponendi võtma:</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="4-poissoni-regressioon.html#cb546-1" aria-hidden="true" tabindex="-1"></a><span class="co"># koefitsiendid saame mudeli objektist kätte coef() funktsiooniga</span></span>
<span id="cb546-2"><a href="4-poissoni-regressioon.html#cb546-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m1))</span></code></pre></div>
<pre><code>##  (Intercept) genderfemale 
##    1.8825911    0.7810027</code></pre>
<p>Vabaliige on <span class="math inline">\(Y\)</span> väärtus kui <span class="math inline">\(x\)</span> on <span class="math inline">\(0\)</span>. Kuna mehed on referentsgrupp (ehk siis <span class="math inline">\(0\)</span>), siis kirjeldab vabaliige siinkohal meeste keskmist artiklite arvu. Võime tulemuse <code>dplyr</code>’iga verifitseerida:</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="4-poissoni-regressioon.html#cb548-1" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb548-2"><a href="4-poissoni-regressioon.html#cb548-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">&#39;male&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb548-3"><a href="4-poissoni-regressioon.html#cb548-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(articles))</span></code></pre></div>
<pre><code>##   mean(articles)
## 1       1.882591</code></pre>
<p>Tundub tõesti nii olevat.</p>
<p>Eksponenti võetud <em>genderfemale</em> koefitsient näitab naiste multiplikatiivset erinevust meestest. Ehk siis naiste keskmine artiklite arv peaks olema <span class="math inline">\(1.88 \times 0.78 = 1.47\)</span>. Teiste sõnadega naiste keskmine artiklite arv on <span class="math inline">\(1-0.78 = 22\%\)</span> väiksem kui meestel. Kontrollime üle:</p>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="4-poissoni-regressioon.html#cb550-1" aria-hidden="true" tabindex="-1"></a>phd <span class="sc">%&gt;%</span> </span>
<span id="cb550-2"><a href="4-poissoni-regressioon.html#cb550-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">&#39;female&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb550-3"><a href="4-poissoni-regressioon.html#cb550-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(articles))</span></code></pre></div>
<pre><code>##   mean(articles)
## 1       1.470309</code></pre>
<p>Jälle sama tulemus.</p>
<p>Mida me veel tulemist näeme ja näha tahame? Eelkõige huvitab meid muidugi see, kas meie tulemused on statistiliselt usaldusväärsed. Regressioonikordajate statistilise olulisuse hindamiseks on meil analoogselt logistilise regressiooni väljundiga kasutada z-test, mis testib kas regressioonikordaja on oluliselt erinev nullist. Näeme nii teststatistikut (z-väärtust), kui ka z-testi iseloomustavat <em>p</em>-väärtust. <em>p</em> väärtused (tulp <code>Pr(&gt;|z|)</code>) on nii vabaliikme kui regressioonikoefitsiendi puhul oluliselt väiksemad kui <span class="math inline">\(0.05\)</span>, misläbi saame järeldada, et usaldusnivool <span class="math inline">\(95\%\)</span> on meie mudeli koefitsiendid statistiliselt oluliselt erinevad nullist<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a>, ehk siis sugu mõjutab oluliselt avaldatud artiklite arvu. Kui koefitsient ei oleks statistiliselt oluline (<span class="math inline">\(p &gt; 0.05\)</span>), siis peaksime järeldama, et meie koefitsient ei erine oluliselt nullist ning seost sõltumatu ja sõltuva tunnuse vahel ei ole.</p>
<p>Sama järelduse saaksime tegelikult teha ka z-väärtuste ja standardvigade (tulp <code>Std. Error</code>) põhjal. Mida väiksem on z-väärtus, seda väiksem on <em>p</em>. Ja kui z-väärtus on (absoluutarvuna) suurem kui <span class="math inline">\(1.96\)</span>, siis on <em>p</em> on väiksem kui <span class="math inline">\(0.05\)</span>. Ning z-väärtus (ja z-test) omakorda tuleneb standardveast: <span class="math inline">\(\frac{-0.24718}{0.05187} = -4.765\)</span>.</p>
<p>Aga vaatame oma mudelit edasi. Lisame ka teised sõltumatud tunnused:</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="4-poissoni-regressioon.html#cb552-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender<span class="sc">+</span>prestige<span class="sc">+</span>married<span class="sc">+</span>kids2<span class="sc">+</span>mentor, <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> phd)</span>
<span id="cb552-2"><a href="4-poissoni-regressioon.html#cb552-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender + prestige + married + kids2 + 
##     mentor, family = poisson(), data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4477  -1.5669  -0.3587   0.5705   5.4715  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.306243   0.103093   2.971  0.00297 ** 
## genderfemale -0.217925   0.054717  -3.983 6.81e-05 ***
## prestige      0.010275   0.026460   0.388  0.69776    
## marriedyes    0.151697   0.063028   2.407  0.01609 *  
## kids2Jah     -0.249563   0.063342  -3.940 8.15e-05 ***
## mentor        0.025817   0.002019  12.788  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1640.9  on 909  degrees of freedom
## AIC: 3320.7
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Näeme, et ülikooli maine ei mõjuta statistiliselt oluliselt artiklite arvu. Ka abielustaatus on suhteliselt piiripealse mõjuga. Jätame maine tunnuse mudelist välja (tahame alati leida võimalikult lihtsa mudeli, seega tunnused, mis mudelisse ei ei panusta, jätame välja).</p>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="4-poissoni-regressioon.html#cb554-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender<span class="sc">+</span>married<span class="sc">+</span>kids2<span class="sc">+</span>mentor, <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> phd)</span></code></pre></div>
<p>Kontrollime igaks juhuks ka <code>anova()</code>-ga, kas maine tunnuse väljajätmine ikka oli õigustatud:</p>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="4-poissoni-regressioon.html#cb555-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m3, m2, <span class="at">test =</span> <span class="st">&#39;Chisq&#39;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: articles ~ gender + married + kids2 + mentor
## Model 2: articles ~ gender + prestige + married + kids2 + mentor
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1       910     1641.1                     
## 2       909     1640.9  1  0.15093   0.6976</code></pre>
<p>Hii-ruut test ütleb meile, et keerulisema ja lihtsama mudeli vahel ei ole statistiliselt olulist erinevust (<span class="math inline">\(p &gt; 0.05\)</span>), seega võime tunnuse vabalt välja jätta.</p>
<p>Näeme, et nii sugu, abielustaatus, laste arv, kui ka juhendaja publikatsioonide arv mõjutavad artiklite arvu oluliselt. Kontrollime igaks juhuks ka soo ja laste olemasolu koosmõju:</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="4-poissoni-regressioon.html#cb557-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender<span class="sc">*</span>kids2<span class="sc">+</span>married<span class="sc">+</span>mentor, <span class="at">family =</span> <span class="fu">poisson</span>(), <span class="at">data =</span> phd)</span>
<span id="cb557-2"><a href="4-poissoni-regressioon.html#cb557-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender * kids2 + married + mentor, family = poisson(), 
##     data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4995  -1.5593  -0.3582   0.5639   5.4570  
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)            0.34220    0.06249   5.476 4.35e-08 ***
## genderfemale          -0.22492    0.06299  -3.571 0.000356 ***
## kids2Jah              -0.25695    0.07148  -3.595 0.000325 ***
## marriedyes             0.14875    0.06291   2.365 0.018045 *  
## mentor                 0.02601    0.00196  13.268  &lt; 2e-16 ***
## genderfemale:kids2Jah  0.02522    0.12539   0.201 0.840628    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1641.0  on 909  degrees of freedom
## AIC: 3320.8
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Koosmõju koefitsient ei ole statistiliselt oluline, seega jääme mudeli m3 juurde:</p>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="4-poissoni-regressioon.html#cb559-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender + married + kids2 + mentor, family = poisson(), 
##     data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.5080  -1.5615  -0.3626   0.5614   5.4494  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.33873    0.06011   5.635 1.75e-08 ***
## genderfemale -0.21864    0.05470  -3.997 6.42e-05 ***
## marriedyes    0.14953    0.06279   2.381   0.0172 *  
## kids2Jah     -0.25029    0.06332  -3.953 7.73e-05 ***
## mentor        0.02600    0.00196  13.268  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1641.1  on 910  degrees of freedom
## AIC: 3318.8
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Järgmiseks võtame mudeli koefitsientide eksponendid, et neid natukene inimlikumal kujul kuvada ja tõlgendada:</p>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="4-poissoni-regressioon.html#cb561-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m3))</span></code></pre></div>
<pre><code>##  (Intercept) genderfemale   marriedyes     kids2Jah       mentor 
##    1.4031677    0.8036087    1.1612850    0.7785778    1.0263406</code></pre>
<p>Mida need koefitsiendid meile ütlevad?</p>
<ul>
<li>Vabaliige on antud näite puhul artiklite arv juhul kui kõikide sõltumatute tunnuste väärtused on nullid (ehk siis kõik kategoorilised tunnused on referentsväärtusega ja pidevtunnused lihtsalt nullid). Konkreetsel juhul on see ka sisukas tulemus, kuna mudeli ainsa pidevtunnuse nullväärtus on täiesti realistilik (juhendaja artiklite arv võib vabalt <span class="math inline">\(0\)</span> olla). Aga üldiselt see pigem nii ei ole (mida me hakkame peale <span class="math inline">\(Y\)</span> väärtusega, mis kehtib olukorras kus vanus või kehakaal on <span class="math inline">\(0\)</span>). Seega, meie mudeli järgi on vallaliste, ilma lasteta meeste, kelle juhendajad pole viimase kolme aasta jooksul ühtegi publikatsiooni avaldanud, artiklite arv keskmiselt 1.4.</li>
<li>Naiste keskmine publikatsioonide arv (hoides teisi tunnuseid konstantsetena) on keskmiselt 20% väiksem (<span class="math inline">\(1-0.8 = 0.2 = 20\%\)</span>) kui meestel.</li>
<li>Abielus doktorantide keskmine publikatsioonide arv on <span class="math inline">\(1.16\)</span> ehk <span class="math inline">\(16\%\)</span> suurem kui vallalistel doktorantidel.</li>
<li>Laste olemasolu pärsib artiklite avaldamist keskmiselt <span class="math inline">\(22\%\)</span> võrra.</li>
<li>Iga juhendaja lisanduv artikkel tõstab juhendatava publitseerimisvõimekust <span class="math inline">\(2\%\)</span> võrra.</li>
</ul>
</div>
</div>
<div id="mudeli-eelduste-kontroll" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Mudeli eelduste kontroll<a href="4-poissoni-regressioon.html#mudeli-eelduste-kontroll" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="üledispersioon" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Üledispersioon<a href="4-poissoni-regressioon.html#üledispersioon" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Mudeli üledispersioon (<em>overdispersion</em>) on olukord, kus mudeli dispersioon on suurem kui mudeli aluseks olev jaotusfunktsioon eeldaks. Kui see on nii, siis on mudeli standardvead tõenäoliselt liiga väikesed (ja seega mudeli alusel tehtavad järldused valed). Üledispersiooni olemasolu saame kontrollida võrreldes jääkhälbimust (<em>Residual deviance</em>) ja selle vabadusastemid (<em>degrees of freedom</em> ehk <em>df</em>). Kui need on enam-vähem võrdsed, ehk <span class="math inline">\(\frac{\text{Residual deviance}}{\text{df}} \approx 1\)</span>, siis üledispersiooni ei ole. Aga kui see suhe on oluliselt suurem kui <span class="math inline">\(1\)</span>, siis on tegemist probleemiga. Juhul kui taoline olukord esineb, peaksime Poissoni mudeli asemel kasutama <em>quasipoisson</em>’i mudelit, kus üledispersiooni on eraldi dispersiooni parameetrina mudelis arvesse võetud. Ka meie näite puhul on tegemist kerge üledispersiooniga (mitte küll väga suurega, aga siiski), seega võiksime kasutada quasipoissonit:</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="4-poissoni-regressioon.html#cb563-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender<span class="sc">+</span>married<span class="sc">+</span>kids2<span class="sc">+</span>mentor, <span class="at">family =</span> quasipoisson, <span class="at">data =</span> phd)</span>
<span id="cb563-2"><a href="4-poissoni-regressioon.html#cb563-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender + married + kids2 + mentor, family = quasipoisson, 
##     data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.5080  -1.5615  -0.3626   0.5614   5.4494  
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.338732   0.081482   4.157 3.53e-05 ***
## genderfemale -0.218643   0.074151  -2.949  0.00327 ** 
## marriedyes    0.149527   0.085110   1.757  0.07928 .  
## kids2Jah     -0.250286   0.085834  -2.916  0.00363 ** 
## mentor        0.026000   0.002656   9.788  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 1.837376)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1641.1  on 910  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Näeme, et punkthinnangud ei muutunud, küll aga läksid standardvead suuremaks. See tähendab, et quaipoissoniga meie mudeli täpsusaste kahaneb (või õigemini esialgse, tavalise Poissoni mudeli puhul hindasime me mudeli täpsust üle). Samuti näeme, et tänu sellele ei ole abielustaatuse koefitsient enam <span class="math inline">\(95\%\)</span> usaldusnivoo korral statistiliselt oluline ja peaksime selle tunnuse välja jätma.</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="4-poissoni-regressioon.html#cb565-1" aria-hidden="true" tabindex="-1"></a>m6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(articles<span class="sc">~</span>gender<span class="sc">+</span>kids2<span class="sc">+</span>mentor, <span class="at">family =</span> quasipoisson, <span class="at">data =</span> phd)</span>
<span id="cb565-2"><a href="4-poissoni-regressioon.html#cb565-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = articles ~ gender + kids2 + mentor, family = quasipoisson, 
##     data = phd)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4818  -1.5758  -0.3663   0.5443   5.5757  
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.423844   0.064597   6.561 8.93e-11 ***
## genderfemale -0.233279   0.073885  -3.157  0.00164 ** 
## kids2Jah     -0.179615   0.076785  -2.339  0.01954 *  
## mentor        0.025776   0.002659   9.695  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 1.843047)
## 
##     Null deviance: 1817.4  on 914  degrees of freedom
## Residual deviance: 1646.8  on 911  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div id="mudeli-sobivus-model-fit" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Mudeli sobivus (<em>model fit</em>)<a href="4-poissoni-regressioon.html#mudeli-sobivus-model-fit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Mudeli sobivust andmetega (<em>goodness of fit</em>) saame analoogselt logistilise regressiooniga hinnata jääkhälbimuse (<em>Residual deviance</em>) abil:</p>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="4-poissoni-regressioon.html#cb567-1" aria-hidden="true" tabindex="-1"></a>res_dev <span class="ot">&lt;-</span> <span class="fu">deviance</span>(m6)</span>
<span id="cb567-2"><a href="4-poissoni-regressioon.html#cb567-2" aria-hidden="true" tabindex="-1"></a>res_df <span class="ot">&lt;-</span> <span class="fu">df.residual</span>(m6)</span>
<span id="cb567-3"><a href="4-poissoni-regressioon.html#cb567-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(res_dev, res_df, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 5.095965e-45</code></pre>
<p>Näeme, et <em>p</em>-väärtus on väiksem kui <span class="math inline">\(0.05\)</span>, mis tähendab, et meie mudel ei sobitu andmetega väga hästi (siin tahame, et <em>p</em>-väärtus oleks võimalikult suur). Reaaleluliste andmetega ongi tegelikult väga keeruline hästi sobituvat mudelit leida. Seega üldjuhul me lihtsalt lepime, et meie mudel ei ole täiuslik ja jätame selle testi tähelepanuta.</p>
<div id="mudeli-statistiline-olulisus-1" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Mudeli statistiline olulisus<a href="4-poissoni-regressioon.html#mudeli-statistiline-olulisus-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Mudeli statistilist olulisust saame jällegi hinnata analoogselt logistilisele regressioonil hälbimuse näitajate abil. Võrdleme nullmudeli hälbimust (<em>Null deviance</em>) ja jääkhälbimust (<em>Residual deviance</em>). Nullmudeli hälbimus hinnatud <span class="math inline">\(Y\)</span> hälbimust tegelikest <span class="math inline">\(Y\)</span> väärtustest juhul kui ühtegi prediktorit mudelis ei ole. Seega kahe hälbimuse vahe näitab kui palju meie mudel tänu sõltumatutele tunnustele paremaks on läinud. See hälbumuste vahe on jälle jaotunud hii-ruut jaotsue alusel, mille vabadusastemeteks on nullmudeli ja hinnatava mudeli vabadusastmete vahe.</p>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="4-poissoni-regressioon.html#cb569-1" aria-hidden="true" tabindex="-1"></a>dev_vahe <span class="ot">&lt;-</span> m6<span class="sc">$</span>null.deviance <span class="sc">-</span> m6<span class="sc">$</span>deviance</span>
<span id="cb569-2"><a href="4-poissoni-regressioon.html#cb569-2" aria-hidden="true" tabindex="-1"></a>df_vahe <span class="ot">&lt;-</span> m6<span class="sc">$</span>df.null<span class="sc">-</span>m6<span class="sc">$</span>df.residual</span>
<span id="cb569-3"><a href="4-poissoni-regressioon.html#cb569-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(dev_vahe, df_vahe, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 9.269198e-37</code></pre>
<p><em>p</em>-väärtus on väiksem kui <span class="math inline">\(0.05\)</span>, seega nullmudel ja meie mudel erinevad olulisel määral ning võime järeldada, et meie mudel on statistiliselt oluline.</p>
</div>
<div id="jääkide-jaotus-1" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Jääkide jaotus<a href="4-poissoni-regressioon.html#jääkide-jaotus-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Poissoni mudeli üheks eelduseks olid üksteisest sõltumatud ja normaaljaotuse järgi jaotunud jäägid.</p>
<p>Paneme joonisele mudeli jäägid (hälbimused) ja (log) prognoositud väärtused. Jäägid peaksid üle prognoositud väärtuste suhteliselt ühtlaselt jaotuma ning mingit selgelt eristuvat mustrit ei tohiks täheldada. Antud juhul ei ole olukord just ideaalne, aga ka mitte kõige hullem. Näeme, et prognoositud väärtuste paremas otsas koonduvad jäägid pigem allapoole, samas jääkide variatiivsus on keskjoonest kõrgemal mõnevõrra suurem. Võib eeldada, et nad ei ole päris normaaljaotuse järgi jaotunud.</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="4-poissoni-regressioon.html#cb571-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(m6, <span class="at">type=</span><span class="st">&quot;deviance&quot;</span>)</span>
<span id="cb571-2"><a href="4-poissoni-regressioon.html#cb571-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(<span class="fu">predict</span>(m6)), res)</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Kontrollime seda ka histogrammiga:</p>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="4-poissoni-regressioon.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(res)</span></code></pre></div>
<p><img src="03-poisson_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Ka siit nähtub, et jäägid ei ole tõesti päris normaalselt jaotunud.</p>
<p>Lõppkokkuvõtteks tuleb tõdeda, et meie mudel ei ole päris ideaalne - ei sobitu kõige paremini andmetega ning ka jääkide struktuur jätab soovida. Põhjus võib olla näiteks selles, et mõni oluline sõltumatu tunnus on mudelist puudu või ka asjaolu, et sõltuva tunnuse jaotus ei vastanud väga hästi Poissoni jaotusele.</p>

</div>
</div>
</div>



<div class="footnotes">
<hr />
<ol start="14">
<li id="fn14"><p>Ka kategoriaalsetest tunnustest moodustatud risttabelite sagedused on loendilised väärtused. Taoliste risttabelite sageduste baasil moodustatud mudeleid kutsutakse log-lineaarseteks mudeliteks. Lisaks loenditele kasutatakse Poissoni regressiooni ka määrade (<em>rates</em>) mudeldamiseks, kuna määrasid võib käsitleda kui standardiseeritud loendeid. Siinkohal me taolisi mudeleid lähemalt ei käsitle, aga olgu see lihtsalt ära mainitud.<a href="4-poissoni-regressioon.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p>Loendiline tunnus <span class="math inline">\(Y\)</span> järgib Poissoni jaotust, mille puhul <span class="math inline">\(E(Y)=Var(Y)=\lambda\)</span>, kus <span class="math inline">\(\lambda\)</span> on nn keskmine loend (keskmine kursuse suurus, järjekorra pikkus, laste arv). Seega Poissoni jaotusega tunnuse puhul peaks keskmine ja dispersioon võrdsed olema ning suurem keskmine tähendab ka suuremat dispersioon.<a href="4-poissoni-regressioon.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p><span class="math inline">\(log(Y_i)\)</span> ei ole siin sama mis lineaarse regressiooni puhul log-transformeeritud tunnus (kui me kasutame analüüsis eelnevalt logaritmitud sõltuvat tunnust). Teine ja sellest aspektist võib-olla selgem notatsioon oleks <span class="math inline">\(log(E(Y))=\beta_0+\beta_1 x_i\)</span>, millest nähtub, et me peame logaritmima <span class="math inline">\(Y\)</span> oodatavat väärtust (<em>expected value</em>) ehk <span class="math inline">\(Y\)</span> keskmist. Keskmine logaritmitud <span class="math inline">\(Y\)</span> ja logaritm keskmisest <span class="math inline">\(Y\)</span>-ist ei ole aga samad asjad (võite järgi proovida: <code>mean(log(c(1,2,3,4)))</code> vs <code>log(mean(c(1,2,3,4)))</code>).<a href="4-poissoni-regressioon.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>Paljude nullidega tunnuse puhul oleks mõistlikum kasutada näiteks <em>zero-inflated Poisson</em>’i regressiooni (<code>zeroinfl()</code> funktsioon <em>pscl</em> paketis) või <em>negative binomial</em> regressiooni (<code>glm.nb()</code> funktsioon <em>MASS</em> paketis)<a href="4-poissoni-regressioon.html#fnref17" class="footnote-back">↩︎</a></p></li>
<li id="fn18"><p>Long, J.S. (1997). The Origin of Sex Differences in Science. Social Forces, 68, 1297–1315.<a href="4-poissoni-regressioon.html#fnref18" class="footnote-back">↩︎</a></p></li>
<li id="fn19"><p><em>p</em>-väärtus ütleb meile, et juhul kui nullhüpotees oleks tõsi (antud juhul on nullhüpoteesiks, et tunnuste vahel ei ole seost, st regressioonikoefitsient on <span class="math inline">\(0\)</span>), siis saaksime sellise tulemuse nagu me saime (täpsemalt öeldes sellise z-väärtuse) tõenäosusega mis on võrdne <em>p</em>-väärtusega. Kui <em>p</em>-väärtus on näiteks <span class="math inline">\(0.05\)</span>, siis uuringut korrates saaksime sellise tulemuse <span class="math inline">\(5\%\)</span> kordadest. Antud juhul on <em>p</em>-väärtus oluliselt väiksem kui <span class="math inline">\(0.5\)</span>, st tõenäosus, et meie regressioonikordaja on tegelikult <span class="math inline">\(0\)</span>, on hästi väike.<a href="4-poissoni-regressioon.html#fnref19" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="3-logistiline-regressioon.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="5-mitmetasandiline-regressioon.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
